---
title: "README"
format: html
editor: visual
---

## Project Description

Our project analyzes the **average age of workforce eligible residents of Vermont and California**. This research explores **urbanization**, provided that California is substantially more urbanized relative to Vermont. We hypothesize that such differences in urbanization are reflected in the workforce age distribution. Specifically, we expect the average age of workforce eligibile population to be greater in Vermont relative to Vermont **(our null hypothesis)**. Such a hypothesis calls for a **one-sided T-test**. We are driven to such research in an effort to gain further insight into the economic conditions of different states. Fundamentally, a higher average age of an eligibile workforce population can indicate an aging population, a shrinking workforce, and slowed prodcutivity. Such conditions, on a broader level, can letter connect to **broader macroeconomic principles** such as human capital capacity and GDP.

## Link to our presentation

**Our final presentation can be found here**:

::: {style="color: green"}
::: {style="color: blue"}
https://docs.google.com/presentation/d/1kUfIBut8nY0T4UytkEbsNNgUaNUDwXSB6UNcHTfr0bY/edit?usp=sharing
:::
:::

## Files & Code:

::: textbox
**Written Report:** Contains an introduction to the project motivation, data, and research question. Includes a brief description of the hypothesis testing, and describes key results. Finishes with a discussion and conclusion regarding the research question at hand, supported by statistical arguments. This section addresses potential flaws in our work, and potential for future research. No code to be run.

**Research Topic (qmd & pdf):** Explores the subject, motivation, and research question of the topic at hand. No code to be run.

**Data File:** Our data file contains *data.qmd*, a document which pulls information from an R library. This data is filtered for the states of California and Vermont. Before the data can be accessed, the following code must be run:
:::

```{r}
library(tidyverse)
```

::: textbox
After this code is run, one may run the small bit of code in the data file to access the data set used for this research.

**Project & Data Analysis:** The file titled *e1_project.Rproj.qmd* holds the bulk of our research. This file pulls CPS information from the library mentioned above, conducts a one-sided t-test, displays box & whisker plots, and graphs a t-distribution plot with critical value. In order for the data to be gathered and for the graphs to plot, each section of code presented must be run in order of display.

**Presentation File:** The presentation file include a Presentation-Link.qmd document, which contains a link to our final presentation slides.

**Gitignore:** The gitignore file is there as a means of listing files that are in the local RStudio, but not in the GitHub Repo. For our case, there were no such files, leaving this document blank.

**Peer Reviews:** Here can be found a checklist of issues that arise from the peer reviews, and a reflection as to how we address these issues.
:::
