---
title: "README"
format: html
editor: visual
---

## Project Description

Our project analyzes the **average age of workforce eligible residents of Vermont and California**. This research explores **urbanization**, provided that California is substantially more urbanized relative to Vermont. We hypothesize that such differences in urbanization are reflected in the workforce age distribution. Specifically, we expect the average age of workforce eligibile population to be greater in Vermont relative to Vermont **(our null hypothesis)**. Such a hypothesis calls for a **one-sided T-test**. We are driven to such research in an effort to gain further insight into the economic conditions of different states. Fundamentally, a higher average age of an eligibile workforce population can indicate an aging population, a shrinking workforce, and slowed prodcutivity. Such conditions, on a broader level, can letter connect to **broader macroeconomic principles** such as human capital capacity and GDP.

## Link to our presentation

**Our final presenation can be found here**:

::: textbox
https://docs.google.com/presentation/d/1kUfIBut8nY0T4UytkEbsNNgUaNUDwXSB6UNcHTfr0bY/edit?usp=sharing
:::

## Outline

Our project and data analysis can be found in **Project.Rproj.qmd**

This file contains our **hypothesis testing.** Here, you can finding the following information:

::: textbox
CPS Library Pull
One-Sided T-Test 
Box and Whisker Plots
Confidence Intervals 
T-Distribution Plot w/ Critical Value
:::
